### ISSUE TITLE
LICENSE files are missing

### ISSUE THREAD

**Issue by alebastr** [psychon/as-raw-xcb-connection#6]
The repository doesn't include any LICENSE files. That's not ok with MIT and doesn't allow us in Fedora to redistribute the crate.

Please, consider adding the license files. Thanks in advance!

**Comment by psychon** [comment]
I added a `license` field to `Cargo.toml` in 319172e1. @notgull already did some changes before that, so I opened #7 to add license files and requested a review from @notgull 

> That's not ok with MIT 

IANAL, but I don't think that's okay with Apache 2.0 either. ;-)  (Well, the text in Apache 2.0 is a lot more complicated so this might actually be okay since Apache 2.0 has stuff like "If the Work includes a NOTICE text file" while the MIT file refers to itself".

At least both licenses say something like "this notice must be kept".

@alebastr I feel like you will be fighting an uphill battle. I interpret https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields as "things are fine the way they already are". Put differently, the cargo team seems to thing that the `license` field is enough and no `license-file` is required.

**Comment by alebastr** [comment]
Thanks!

> @alebastr I feel like you will be fighting an uphill battle. I interpret https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields as "things are fine the way they already are". Put differently, the cargo team seems to thing that the `license` field is enough and no `license-file` is required.

Sorry if I made it look like I want the `license-files` field to be set. The battle is already lost (the cargo team's stance is that the fields are mutually exclusive), so our packaging tools never relied on that. We only need the files with the copyright notices, as we cannot add these downstream.

**Comment by psychon** [comment]
> the cargo team's stance is that the fields are mutually exclusive

Ah, I didn't notice. My thought process was something like "if I add this file, do I have to tell cargo about it... let's check the reference... nah, doesn't seem like it". Thanks for this info.
